version: '3'
services:
  # Krakend Service
  lampo-krakend:
    env_file:
      - ./.env
    build:
      context: ./
      dockerfile: docker/Dockerfile
    container_name: lampo-krakend
    ports:
      - ${PORT}:8080